### ISSUE TITLE
PocketMine-MP 5 support

### ISSUE THREAD

**Issue by J1b1x** [IvanCraft623/fakeblocks#2]

**Comment by kostamax27** [comment]
#3

**Comment by IvanCraft623** [comment]
Done by 15df2689184abb5a7cf2e5142afdc7ee7e8f5d5d

**Comment by kostamax27** [comment]
> Done by [15df268](https://github.com/IvanCraft623/fakeblocks/commit/15df2689184abb5a7cf2e5142afdc7ee7e8f5d5d)

Hooray you're back :)
